@extends('layouts.app-dashboard')
@section('title', 'Detail Laporan ATM')
@section('nav-links')
<a href="{{ route('admin.dashboard') }}" class="px-4 py-2 rounded-xl text-sm font-semibold text-gray-600 hover:text-blue-600 hover:bg-blue-50 transition-all">Dashboard</a>
<a href="{{ route('admin.monitoring.laporan') }}" class="px-4 py-2 rounded-xl text-sm font-bold bg-gradient-to-r from-blue-500 to-indigo-600 text-white shadow-md hover:shadow-lg transition-all">Monitoring Laporan</a>
@endsection
@section('mobile-nav-links')
<a href="{{ route('admin.dashboard') }}" class="block px-4 py-3 rounded-xl text-base font-semibold text-gray-700 hover:bg-blue-50 hover:text-blue-600 transition-all mb-2">Dashboard</a>
<a href="{{ route('admin.monitoring.laporan') }}" class="block px-4 py-3 rounded-xl text-base font-bold bg-gradient-to-r from-blue-500 to-indigo-600 text-white mb-2">Monitoring Laporan</a>
@endsection
@section('content')
<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
<div class="mb-8 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h1 class="text-3xl md:text-4xl font-bold bg-gradient-to-r from-emerald-600 to-teal-600 bg-clip-text text-transparent">📸 Detail Laporan</h1><p class="mt-2 text-gray-600">{{ $laporan->atm->nama_atm }} • {{ $laporan->tanggal->format('d F Y') }}</p></div><a href="{{ route('admin.monitoring.laporan') }}" class="inline-flex items-center justify-center px-5 py-2.5 bg-gradient-to-r from-gray-600 to-gray-700 text-white rounded-xl font-semibold hover:from-gray-700 hover:to-gray-800 transition shadow-lg space-x-2 self-start"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path></svg><span>Kembali</span></a></div>
<div class="grid grid-cols-1 lg:grid-cols-3 gap-6"><div class="lg:col-span-1 space-y-6"><div class="bg-white rounded-2xl shadow-lg border border-gray-100 overflow-hidden"><div class="bg-gradient-to-r from-blue-500 to-indigo-500 px-6 py-4"><div class="flex items-center space-x-3"><div class="w-10 h-10 bg-white/20 rounded-xl flex items-center justify-center backdrop-blur-sm"><svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4"></path></svg></div><h3 class="text-base font-bold text-white">Info ATM</h3></div></div><div class="p-6 space-y-4"><div class="p-3 bg-blue-50 rounded-xl border border-blue-100"><p class="text-xs font-bold text-blue-600 uppercase tracking-wider mb-1">🏧 Nama ATM</p><p class="text-sm font-bold text-gray-900">{{ $laporan->atm->nama_atm }}</p></div><div class="p-3 bg-gray-50 rounded-xl border border-gray-200"><p class="text-xs font-bold text-gray-600 uppercase tracking-wider mb-1">🗺️ Lokasi</p><p class="text-sm text-gray-700">{{ $laporan->atm->lokasi }}</p></div>@if($laporan->atm->alamat_lengkap)<div class="p-3 bg-gray-50 rounded-xl border border-gray-200"><p class="text-xs font-bold text-gray-600 uppercase tracking-wider mb-1">📮 Alamat</p><p class="text-sm text-gray-700 leading-relaxed">{{ $laporan->atm->alamat_lengkap }}</p></div>@endif<div class="p-3 bg-gray-50 rounded-xl border border-gray-200"><p class="text-xs font-bold text-gray-600 uppercase tracking-wider mb-2">📍 Area</p><span class="px-3 py-1 bg-blue-500 text-white text-sm font-bold rounded-full">{{ $laporan->atm->area->nama_area }}</span></div></div></div>
<div class="bg-white rounded-2xl shadow-lg border border-gray-100 overflow-hidden"><div class="bg-gradient-to-r from-green-500 to-teal-500 px-6 py-4"><div class="flex items-center space-x-3"><div class="w-10 h-10 bg-white/20 rounded-xl flex items-center justify-center backdrop-blur-sm"><svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path></svg></div><h3 class="text-base font-bold text-white">Cleaning Service</h3></div></div><div class="p-6 space-y-4"><div class="flex items-center space-x-3 p-4 bg-green-50 rounded-xl border border-green-200"><img src="{{ $laporan->csProfile->foto === 'default-avatar.png' ? 'https://ui-avatars.com/api/?name=' . urlencode($laporan->csProfile->user->name) . '&size=120&background=10b981&color=fff' : asset('storage/' . $laporan->csProfile->foto) }}" alt="{{ $laporan->csProfile->user->name }}" class="w-14 h-14 rounded-full border-2 border-green-300 shadow-lg object-cover"><div class="flex-1"><p class="text-sm font-bold text-gray-900">{{ $laporan->csProfile->user->name }}</p><p class="text-xs text-gray-600">{{ $laporan->csProfile->user->email }}</p></div></div><div class="grid grid-cols-2 gap-3"><div class="p-3 bg-gray-50 rounded-xl border border-gray-200 text-center"><p class="text-xs font-bold text-gray-600 uppercase tracking-wider mb-1">📅 Tanggal</p><p class="text-sm font-bold text-gray-900">{{ $laporan->tanggal->format('d M Y') }}</p></div><div class="p-3 bg-gray-50 rounded-xl border border-gray-200 text-center"><p class="text-xs font-bold text-gray-600 uppercase tracking-wider mb-1">⏰ Jam Absen</p><p class="text-sm font-bold text-gray-900">{{ $laporan->absensi->jam_absen }}</p></div></div><div class="p-3 bg-gray-50 rounded-xl border border-gray-200"><p class="text-xs font-bold text-gray-600 uppercase tracking-wider mb-1">📝 Input Laporan</p><p class="text-sm text-gray-700">{{ $laporan->created_at->format('H:i') }} WIB</p></div></div></div>
@if($laporan->catatan)<div class="bg-white rounded-2xl shadow-lg border border-gray-100 overflow-hidden"><div class="bg-gradient-to-r from-yellow-500 to-orange-500 px-6 py-4"><div class="flex items-center space-x-3"><div class="w-10 h-10 bg-white/20 rounded-xl flex items-center justify-center backdrop-blur-sm"><svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg></div><h3 class="text-base font-bold text-white">Catatan / Kendala</h3></div></div><div class="p-6"><div class="p-4 bg-yellow-50 border-l-4 border-yellow-400 rounded-xl"><p class="text-sm text-gray-700 leading-relaxed">{{ $laporan->catatan }}</p></div></div></div>@endif</div>
<div class="lg:col-span-2"><div class="bg-white rounded-2xl shadow-lg border border-gray-100 overflow-hidden"><div class="bg-gradient-to-r from-purple-500 to-pink-500 px-6 py-4"><div class="flex items-center space-x-3"><div class="w-9 h-9 bg-white/20 rounded-xl flex items-center justify-center backdrop-blur-sm"><svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path></svg></div><h3 class="text-base font-bold text-white">📸 Dokumentasi Pembersihan</h3></div></div><div class="p-6 space-y-6"><div><div class="flex items-center mb-3"><div class="w-9 h-9 bg-gradient-to-br from-red-400 to-red-600 rounded-xl flex items-center justify-center"><span class="text-white font-bold text-sm">1</span></div><h4 class="ml-3 text-sm font-bold text-gray-900">🔴 Sebelum Dibersihkan</h4></div><div class="rounded-2xl overflow-hidden border-2 border-gray-300 shadow-lg"><img src="{{ asset('storage/' . $laporan->foto_sebelum) }}" alt="Sebelum" class="w-full h-auto cursor-pointer hover:opacity-90 transition" onclick="openModal('{{ asset('storage/' . $laporan->foto_sebelum) }}')"></div><p class="mt-2 text-xs text-gray-500 text-center">👆 Klik untuk memperbesar</p></div><div><div class="flex items-center mb-3"><div class="w-9 h-9 bg-gradient-to-br from-green-400 to-green-600 rounded-xl flex items-center justify-center"><span class="text-white font-bold text-sm">2</span></div><h4 class="ml-3 text-sm font-bold text-gray-900">🟢 Sesudah Dibersihkan</h4></div><div class="rounded-2xl overflow-hidden border-2 border-gray-300 shadow-lg"><img src="{{ asset('storage/' . $laporan->foto_sesudah) }}" alt="Sesudah" class="w-full h-auto cursor-pointer hover:opacity-90 transition" onclick="openModal('{{ asset('storage/' . $laporan->foto_sesudah) }}')"></div><p class="mt-2 text-xs text-gray-500 text-center">👆 Klik untuk memperbesar</p></div><div><div class="flex items-center mb-3"><div class="w-9 h-9 bg-gradient-to-br from-blue-400 to-blue-600 rounded-xl flex items-center justify-center"><span class="text-white font-bold text-sm">3</span></div><h4 class="ml-3 text-sm font-bold text-gray-900">🔵 Lokasi ATM</h4></div><div class="rounded-2xl overflow-hidden border-2 border-gray-300 shadow-lg"><img src="{{ asset('storage/' . $laporan->foto_lokasi) }}" alt="Lokasi" class="w-full h-auto cursor-pointer hover:opacity-90 transition" onclick="openModal('{{ asset('storage/' . $laporan->foto_lokasi) }}')"></div><p class="mt-2 text-xs text-gray-500 text-center">👆 Klik untuk memperbesar</p></div></div></div></div></div>
</div>
<div id="imageModal" class="hidden fixed inset-0 bg-black/90 backdrop-blur-sm z-50 flex items-center justify-center p-4" onclick="closeModal()"><div class="relative max-w-5xl w-full"><button onclick="closeModal()" class="absolute -top-12 right-0 text-white bg-white/10 hover:bg-white/20 rounded-full p-2 transition"><svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg></button><img id="modalImage" src="" alt="Zoom" class="w-full h-auto rounded-2xl shadow-2xl"></div></div>
<script>function openModal(src){document.getElementById('modalImage').src=src;document.getElementById('imageModal').classList.remove('hidden')}function closeModal(){document.getElementById('imageModal').classList.add('hidden')}document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()})</script>
@endsection
