<!DOCTYPE html>
<html lang="id">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Laporan Harian - {{ $tanggal->format('d F Y') }}</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:Arial,sans-serif;font-size:12px;line-height:1.4;padding:20px}.header{text-align:center;margin-bottom:20px;border-bottom:3px solid #3b82f6;padding-bottom:15px}.header h1{font-size:20px;margin-bottom:8px;color:#1e40af}.header p{font-size:13px;color:#64748b}.info-box{background:linear-gradient(to right,#eff6ff,#dbeafe);padding:15px;margin-bottom:20px;border-radius:8px;border-left:4px solid #3b82f6}.info-box p{margin-bottom:5px;font-size:12px}.info-box strong{color:#1e40af}table{width:100%;border-collapse:collapse;margin-bottom:25px}table th{background:linear-gradient(to right,#3b82f6,#6366f1);color:white;padding:10px 8px;text-align:left;font-size:11px;border:1px solid #2563eb}table td{padding:8px;border:1px solid #e5e7eb;font-size:11px}table tr:nth-child(even){background:#f8fafc}.status-hadir{background:#d1fae5;color:#065f46;padding:3px 8px;border-radius:4px;font-size:10px;font-weight:bold}.status-izin{background:#fef3c7;color:#92400e;padding:3px 8px;border-radius:4px;font-size:10px;font-weight:bold}.status-sakit{background:#fee2e2;color:#991b1b;padding:3px 8px;border-radius:4px;font-size:10px;font-weight:bold}.section-title{margin:25px 0 12px;font-size:15px;color:#1e40af;font-weight:bold;border-bottom:2px solid #3b82f6;padding-bottom:5px}.footer{margin-top:40px;text-align:right}.signature{margin-top:70px;text-align:center}.signature-line{border-top:2px solid #000;width:200px;margin:0 auto;margin-top:70px}@media print{body{padding:0}.no-print{display:none}@page{margin:1.5cm}}.print-button{position:fixed;top:20px;right:20px;background:linear-gradient(to right,#3b82f6,#6366f1);color:white;border:none;padding:12px 24px;border-radius:8px;cursor:pointer;font-size:14px;box-shadow:0 4px 6px rgba(59,130,246,0.3);font-weight:bold;transition:all 0.3s}.print-button:hover{background:linear-gradient(to right,#2563eb,#4f46e5);box-shadow:0 6px 8px rgba(59,130,246,0.4);transform:translateY(-2px)}</style>
</head>
<body>
<button class="print-button no-print" onclick="window.print()">🖨️ Print / Download PDF</button>
<div class="header"><h1>📊 LAPORAN HARIAN PEMBERSIHAN ATM</h1><p>Sistem Monitoring Cleaning Service ATM</p></div>
<div class="info-box"><p><strong>📅 Tanggal:</strong> {{ $tanggal->format('l, d F Y') }}</p><p><strong>👥 Total Absensi:</strong> {{ $absensis->count() }} CS</p><p><strong>📋 Total Laporan:</strong> {{ $laporans->count() }} ATM</p><p><strong>🖨️ Dicetak:</strong> {{ now()->format('d F Y, H:i') }} WIB</p></div>
<h3 class="section-title">1️⃣ DAFTAR ABSENSI</h3>
<table><thead><tr><th style="width:5%">No</th><th style="width:25%">Nama CS</th><th style="width:15%">Jam Absen</th><th style="width:20%">Area</th><th style="width:15%">Status</th><th style="width:20%">Keterangan</th></tr></thead><tbody>@forelse($absensis as $index => $absensi)<tr><td style="text-align:center">{{ $index + 1 }}</td><td>{{ $absensi->csProfile->user->name }}</td><td>{{ $absensi->jam_absen }}</td><td>{{ $absensi->area->nama_area }}</td><td>@if($absensi->status === 'hadir')<span class="status-hadir">✓ HADIR</span>@elseif($absensi->status === 'izin')<span class="status-izin">⏸ IZIN</span>@else<span class="status-sakit">✗ SAKIT</span>@endif</td><td>{{ $absensi->keterangan ?? '-' }}</td></tr>@empty<tr><td colspan="6" style="text-align:center;padding:20px;color:#9ca3af">Tidak ada data absensi</td></tr>@endforelse</tbody></table>
<h3 class="section-title">2️⃣ LAPORAN PEMBERSIHAN ATM</h3>
<table><thead><tr><th style="width:5%">No</th><th style="width:20%">Nama CS</th><th style="width:15%">Area</th><th style="width:25%">Nama ATM</th><th style="width:15%">Lokasi</th><th style="width:20%">Catatan</th></tr></thead><tbody>@forelse($laporans as $index => $laporan)<tr><td style="text-align:center">{{ $index + 1 }}</td><td>{{ $laporan->csProfile->user->name }}</td><td>{{ $laporan->atm->area->nama_area }}</td><td>{{ $laporan->atm->nama_atm }}</td><td>{{ $laporan->atm->lokasi }}</td><td>{{ $laporan->catatan ?? '-' }}</td></tr>@empty<tr><td colspan="6" style="text-align:center;padding:20px;color:#9ca3af">Tidak ada laporan pembersihan</td></tr>@endforelse</tbody></table>
<div class="footer"><div style="display:inline-block;text-align:center;margin-top:50px"><p style="font-weight:bold;font-size:13px">Jakarta, {{ $tanggal->format('d F Y') }}</p><p style="margin-top:8px;font-size:12px">Koordinator,</p><div class="signature-line"></div><p style="margin-top:8px;font-size:12px">( _________________ )</p></div></div>
</body>
</html>
