@extends('layouts.app-dashboard')
@section('title', 'Tambah Item Inventory')
@section('nav-links')
<a href="{{ route('admin.dashboard') }}" class="px-4 py-2 rounded-xl text-sm font-semibold text-gray-600 hover:text-blue-600 hover:bg-blue-50 transition-all">Dashboard</a>
<a href="{{ route('admin.inventory.index') }}" class="px-4 py-2 rounded-xl text-sm font-bold bg-gradient-to-r from-blue-500 to-indigo-600 text-white shadow-md hover:shadow-lg transition-all">Kelola Inventory</a>
@endsection
@section('mobile-nav-links')
<a href="{{ route('admin.dashboard') }}" class="block px-4 py-3 rounded-xl text-base font-semibold text-gray-700 hover:bg-blue-50 hover:text-blue-600 transition-all mb-2">Dashboard</a>
<a href="{{ route('admin.inventory.index') }}" class="block px-4 py-3 rounded-xl text-base font-bold bg-gradient-to-r from-blue-500 to-indigo-600 text-white mb-2">Kelola Inventory</a>
@endsection
@section('content')
<div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
<div class="mb-8"><h1 class="text-3xl md:text-4xl font-bold bg-gradient-to-r from-cyan-600 to-blue-600 bg-clip-text text-transparent">➕ Tambah Item Inventory</h1><p class="mt-2 text-gray-600">Tambahkan alat atau chemical baru</p></div>
<div class="bg-white rounded-2xl shadow-lg border border-gray-100 overflow-hidden">
<div class="bg-gradient-to-r from-cyan-500 to-blue-500 px-6 py-4"><div class="flex items-center space-x-3"><div class="w-10 h-10 bg-white/20 rounded-xl flex items-center justify-center backdrop-blur-sm"><svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"></path></svg></div><div><h2 class="text-lg font-bold text-white">Form Tambah Item</h2><p class="text-white/70 text-xs">Semua field bertanda * wajib diisi</p></div></div></div>
<form action="{{ route('admin.inventory.store') }}" method="POST">@csrf
<div class="p-6 space-y-6">
<div><label for="nama_item" class="block text-xs font-bold text-gray-600 mb-2 uppercase tracking-wider">📦 Nama Item <span class="text-red-500">*</span></label><input type="text" name="nama_item" id="nama_item" value="{{ old('nama_item') }}" placeholder="Contoh: Sapu, Pembersih Kaca, dll" class="w-full px-4 py-3 bg-gray-50 border-2 border-gray-200 rounded-xl focus:ring-2 focus:ring-cyan-500 focus:border-transparent transition @error('nama_item') border-red-400 @enderror" required>@error('nama_item')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<div><label class="block text-xs font-bold text-gray-600 mb-2 uppercase tracking-wider">🏷️ Jenis <span class="text-red-500">*</span></label><div class="grid grid-cols-1 sm:grid-cols-2 gap-3"><label class="flex items-start p-4 bg-blue-50 border-2 border-blue-200 rounded-xl cursor-pointer hover:bg-blue-100 transition"><input type="radio" name="jenis" value="alat" {{ old('jenis', 'alat') === 'alat' ? 'checked' : '' }} class="mt-1 w-5 h-5 text-blue-600 focus:ring-blue-500"><div class="ml-3"><span class="text-sm font-bold text-blue-900">🔧 Alat</span><p class="text-xs text-blue-700 mt-0.5">Sapu, Pel, Kain Lap, dll</p></div></label><label class="flex items-start p-4 bg-purple-50 border-2 border-purple-200 rounded-xl cursor-pointer hover:bg-purple-100 transition"><input type="radio" name="jenis" value="chemical" {{ old('jenis') === 'chemical' ? 'checked' : '' }} class="mt-1 w-5 h-5 text-purple-600 focus:ring-purple-500"><div class="ml-3"><span class="text-sm font-bold text-purple-900">🧪 Chemical</span><p class="text-xs text-purple-700 mt-0.5">Pembersih, Disinfektan, dll</p></div></label></div>@error('jenis')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<div class="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label for="stok" class="block text-xs font-bold text-gray-600 mb-2 uppercase tracking-wider">📊 Stok Awal <span class="text-red-500">*</span></label><input type="number" name="stok" id="stok" value="{{ old('stok', 0) }}" min="0" class="w-full px-4 py-3 bg-gray-50 border-2 border-gray-200 rounded-xl focus:ring-2 focus:ring-cyan-500 focus:border-transparent transition @error('stok') border-red-400 @enderror" required>@error('stok')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label for="satuan" class="block text-xs font-bold text-gray-600 mb-2 uppercase tracking-wider">📏 Satuan <span class="text-red-500">*</span></label><input type="text" name="satuan" id="satuan" value="{{ old('satuan') }}" placeholder="pcs, liter, botol, kg" class="w-full px-4 py-3 bg-gray-50 border-2 border-gray-200 rounded-xl focus:ring-2 focus:ring-cyan-500 focus:border-transparent transition @error('satuan') border-red-400 @enderror" required>@error('satuan')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div></div>
<div><label for="keterangan" class="block text-xs font-bold text-gray-600 mb-2 uppercase tracking-wider">📝 Keterangan</label><textarea name="keterangan" id="keterangan" rows="3" placeholder="Deskripsi item, merek, spesifikasi..." class="w-full px-4 py-3 bg-gray-50 border-2 border-gray-200 rounded-xl focus:ring-2 focus:ring-cyan-500 focus:border-transparent transition @error('keterangan') border-red-400 @enderror">{{ old('keterangan') }}</textarea><p class="mt-1 text-xs text-gray-500">Opsional - informasi tambahan tentang item</p>@error('keterangan')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<div class="p-4 bg-cyan-50 border-l-4 border-cyan-400 rounded-xl"><div class="flex items-start space-x-3"><div class="w-6 h-6 bg-cyan-500 rounded-lg flex items-center justify-center flex-shrink-0"><svg class="w-4 h-4 text-white" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"/></svg></div><div><p class="text-xs font-bold text-cyan-800 mb-1">💡 Info</p><p class="text-xs text-cyan-700">Item baru akan otomatis dalam status <strong>aktif</strong>. CS dapat langsung mengajukan permintaan untuk item ini.</p></div></div></div>
</div>
<div class="px-6 py-4 bg-gray-50 border-t border-gray-200 flex flex-col sm:flex-row justify-end gap-3"><a href="{{ route('admin.inventory.index') }}" class="inline-flex items-center justify-center px-6 py-3 bg-white border-2 border-gray-300 rounded-xl font-semibold text-sm text-gray-700 hover:bg-gray-50 transition">Batal</a><button type="submit" class="inline-flex items-center justify-center px-8 py-3 bg-gradient-to-r from-cyan-500 to-blue-500 text-white rounded-xl font-bold text-sm hover:from-cyan-600 hover:to-blue-600 transition shadow-lg hover:shadow-xl space-x-2"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path></svg><span>Simpan Item</span></button></div>
</form>
</div>
</div>
@endsection
