@extends('layouts.app-dashboard')
@section('title', 'Edit Item Inventory')
@section('nav-links')
<a href="{{ route('admin.dashboard') }}" class="px-4 py-2 rounded-xl text-sm font-semibold text-gray-600 hover:text-blue-600 hover:bg-blue-50 transition-all">Dashboard</a>
<a href="{{ route('admin.inventory.index') }}" class="px-4 py-2 rounded-xl text-sm font-bold bg-gradient-to-r from-blue-500 to-indigo-600 text-white shadow-md hover:shadow-lg transition-all">Kelola Inventory</a>
@endsection
@section('mobile-nav-links')
<a href="{{ route('admin.dashboard') }}" class="block px-4 py-3 rounded-xl text-base font-semibold text-gray-700 hover:bg-blue-50 hover:text-blue-600 transition-all mb-2">Dashboard</a>
<a href="{{ route('admin.inventory.index') }}" class="block px-4 py-3 rounded-xl text-base font-bold bg-gradient-to-r from-blue-500 to-indigo-600 text-white mb-2">Kelola Inventory</a>
@endsection
@section('content')
<div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
<div class="mb-8"><h1 class="text-3xl md:text-4xl font-bold bg-gradient-to-r from-yellow-600 to-orange-600 bg-clip-text text-transparent">✏️ Edit Item Inventory</h1><p class="mt-2 text-gray-600">Update informasi: {{ $inventory->nama_item }}</p></div>
<div class="bg-white rounded-2xl shadow-lg border border-gray-100 overflow-hidden">
<div class="bg-gradient-to-r from-yellow-500 to-orange-500 px-6 py-4"><div class="flex items-center space-x-3"><div class="w-10 h-10 bg-white/20 rounded-xl flex items-center justify-center backdrop-blur-sm"><svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path></svg></div><div><h2 class="text-lg font-bold text-white">Form Edit Item</h2><p class="text-white/70 text-xs">Update data item yang sudah ada</p></div></div></div>
<form action="{{ route('admin.inventory.update', $inventory->id) }}" method="POST">@csrf @method('PUT')
<div class="p-6 space-y-6">
<div><label for="nama_item" class="block text-xs font-bold text-gray-600 mb-2 uppercase tracking-wider">📦 Nama Item <span class="text-red-500">*</span></label><input type="text" name="nama_item" id="nama_item" value="{{ old('nama_item', $inventory->nama_item) }}" class="w-full px-4 py-3 bg-gray-50 border-2 border-gray-200 rounded-xl focus:ring-2 focus:ring-yellow-500 focus:border-transparent transition @error('nama_item') border-red-400 @enderror" required>@error('nama_item')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<div><label class="block text-xs font-bold text-gray-600 mb-2 uppercase tracking-wider">🏷️ Jenis <span class="text-red-500">*</span></label><div class="grid grid-cols-1 sm:grid-cols-2 gap-3"><label class="flex items-start p-4 {{ old('jenis', $inventory->jenis) === 'alat' ? 'bg-blue-100 border-blue-400' : 'bg-blue-50 border-blue-200' }} border-2 rounded-xl cursor-pointer hover:bg-blue-100 transition"><input type="radio" name="jenis" value="alat" {{ old('jenis', $inventory->jenis) === 'alat' ? 'checked' : '' }} class="mt-1 w-5 h-5 text-blue-600 focus:ring-blue-500"><div class="ml-3"><span class="text-sm font-bold text-blue-900">🔧 Alat</span></div></label><label class="flex items-start p-4 {{ old('jenis', $inventory->jenis) === 'chemical' ? 'bg-purple-100 border-purple-400' : 'bg-purple-50 border-purple-200' }} border-2 rounded-xl cursor-pointer hover:bg-purple-100 transition"><input type="radio" name="jenis" value="chemical" {{ old('jenis', $inventory->jenis) === 'chemical' ? 'checked' : '' }} class="mt-1 w-5 h-5 text-purple-600 focus:ring-purple-500"><div class="ml-3"><span class="text-sm font-bold text-purple-900">🧪 Chemical</span></div></label></div>@error('jenis')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<div class="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label for="stok" class="block text-xs font-bold text-gray-600 mb-2 uppercase tracking-wider">📊 Stok <span class="text-red-500">*</span></label><input type="number" name="stok" id="stok" value="{{ old('stok', $inventory->stok) }}" min="0" class="w-full px-4 py-3 bg-gray-50 border-2 border-gray-200 rounded-xl focus:ring-2 focus:ring-yellow-500 focus:border-transparent transition @error('stok') border-red-400 @enderror" required><p class="mt-1 text-xs text-gray-500">Untuk tambah/kurangi stok, gunakan fitur di halaman detail</p>@error('stok')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label for="satuan" class="block text-xs font-bold text-gray-600 mb-2 uppercase tracking-wider">📏 Satuan <span class="text-red-500">*</span></label><input type="text" name="satuan" id="satuan" value="{{ old('satuan', $inventory->satuan) }}" class="w-full px-4 py-3 bg-gray-50 border-2 border-gray-200 rounded-xl focus:ring-2 focus:ring-yellow-500 focus:border-transparent transition @error('satuan') border-red-400 @enderror" required>@error('satuan')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div></div>
<div><label for="keterangan" class="block text-xs font-bold text-gray-600 mb-2 uppercase tracking-wider">📝 Keterangan</label><textarea name="keterangan" id="keterangan" rows="3" class="w-full px-4 py-3 bg-gray-50 border-2 border-gray-200 rounded-xl focus:ring-2 focus:ring-yellow-500 focus:border-transparent transition @error('keterangan') border-red-400 @enderror">{{ old('keterangan', $inventory->keterangan) }}</textarea>@error('keterangan')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<div class="p-4 bg-gray-50 rounded-xl border-2 border-gray-200"><label class="flex items-start cursor-pointer"><input type="checkbox" name="is_active" value="1" {{ old('is_active', $inventory->is_active) ? 'checked' : '' }} class="mt-1 w-5 h-5 rounded border-gray-300 text-yellow-600 focus:ring-yellow-500"><div class="ml-3"><span class="text-sm font-bold text-gray-900">✅ Item Aktif</span><p class="text-xs text-gray-500 mt-0.5">Nonaktifkan jika item tidak digunakan lagi</p></div></label></div>
</div>
<div class="px-6 py-4 bg-gray-50 border-t border-gray-200 flex flex-col sm:flex-row justify-end gap-3"><a href="{{ route('admin.inventory.index') }}" class="inline-flex items-center justify-center px-6 py-3 bg-white border-2 border-gray-300 rounded-xl font-semibold text-sm text-gray-700 hover:bg-gray-50 transition">Batal</a><button type="submit" class="inline-flex items-center justify-center px-8 py-3 bg-gradient-to-r from-yellow-500 to-orange-500 text-white rounded-xl font-bold text-sm hover:from-yellow-600 hover:to-orange-600 transition shadow-lg hover:shadow-xl space-x-2"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path></svg><span>Update Item</span></button></div>
</form>
</div>
</div>
@endsection
